fix: refat usecase errors
Maua-Dev/port_mss_action pull request #104
Opened 2024-08-22 18:57 UTC by rruthes

2024-08-27 11:15 UTC, MatCMartins commented on src/modules/create_project/app/create_project_usecase.py
Aqui eu acho que é ForbiddenAction para verificações para PO and Scrum

2024-08-27 11:16 UTC, MatCMartins commented on src/modules/get_member/app/get_member_usecase.py
Aqui faltou mudar

2024-08-27 11:18 UTC, MatCMartins commented on src/shared/helpers/errors/usecase_errors.py
Legal, mas onde vcs usaram isso?

2024-08-27 11:26 UTC, MatCMartins commented on src/modules/update_action/app/update_action_usecase.py
Aqui eu acho que seria interessante fazer um novo erro pra admin. Parecido com o UserIsNotBusiness

2024-08-27 11:26 UTC, MatCMartins commented on src/modules/get_history/app/get_history_usecase.py
Aqui eu acho que seria interessante fazer um novo erro pra admin. Parecido com o UserIsNotBusiness. 

A do user.active ta ok

2024-08-27 11:28 UTC, MatCMartins commented on tests/modules/get_history/app/test_get_history_controller.py
Mudar o erro do usecase aqui tbm

2024-08-27 11:29 UTC, MatCMartins commented on tests/modules/get_history/app/test_get_history_usecase.py
Mudar o erro do usecase aqui tbm

2024-08-27 11:29 UTC, MatCMartins commented on tests/modules/update_action/app/test_update_action_controller.py
Mudar o erro do usecase aqui tbm

2024-08-27 11:29 UTC, MatCMartins commented on tests/modules/update_action/app/test_update_action_usecase.py
Mudar o erro do usecase aqui tbm

2024-08-27 11:30 UTC, MatCMartins commented on src/modules/update_member/app/update_member_usecase.py
Aqui eu acho que seria interessante fazer um novo erro pra admin. Parecido com o UserIsNotBusiness.

A do user.active ta ok

2024-08-27 11:30 UTC, MatCMartins commented on tests/modules/update_member/app/test_update_member_controller.py
Mudar o erro do usecase aqui tbm

2024-08-27 11:31 UTC, MatCMartins commented on tests/modules/update_member/app/test_update_member_usecase.py
Mudar o erro do usecase aqui tbm

2024-08-27 11:33 UTC, MatCMartins requested changes
1. A maioria ta legal, pedi algumas mudanças. 
2.  A branch vai dar erro de conflito com a principal. Vcs precisam dar pull com a branch principal e consertar os conflitos de merge

2024-08-28 20:37 UTC, rruthes commented on src/modules/create_project/app/create_project_usecase.py
feito

2024-08-28 20:38 UTC, rruthes commented on src/modules/get_member/app/get_member_usecase.py
feito

2024-08-28 20:38 UTC, rruthes commented on src/modules/update_action/app/update_action_usecase.py
feito

2024-08-28 20:38 UTC, rruthes commented on src/modules/get_history/app/get_history_usecase.py
feito

2024-08-28 20:38 UTC, rruthes commented on src/modules/update_member/app/update_member_usecase.py
feito

2024-08-28 21:48 UTC, rruthes commented on tests/modules/get_history/app/test_get_history_controller.py
feito

2024-08-28 21:48 UTC, rruthes commented on tests/modules/update_action/app/test_update_action_controller.py
feito

2024-08-28 21:48 UTC, rruthes commented on tests/modules/update_action/app/test_update_action_usecase.py
feito

2024-08-28 21:48 UTC, rruthes commented on tests/modules/update_member/app/test_update_member_usecase.py
feito

2024-08-29 13:15 UTC, MatCMartins commented on src/modules/create_project/app/create_project_usecase.py
Aqui vcs poderiam usar o novo para validate_role_admin.

2024-08-29 13:16 UTC, MatCMartins commented on src/modules/delete_project/app/delete_project_usecase.py
Aqui também dava pra usar o novo erro no validate_role_admin

2024-08-29 13:17 UTC, MatCMartins commented on src/modules/get_all_members/app/get_all_members_usecase.py
UserNotAllowed

2024-08-29 13:19 UTC, MatCMartins commented on src/modules/get_history/app/get_history_usecase.py
Aqui vcs trocaram o erro do user active. Podia deixar como estava antes. O outro

2024-08-29 13:19 UTC, MatCMartins commented on src/modules/get_history/app/get_history_usecase.py
Aqui vcs trocaram o erro do user active. Podia deixar como estava antes. O outro q vcs mudaram ta legal agr

2024-08-29 13:21 UTC, MatCMartins commented on src/modules/get_member/app/get_member_usecase.py
Aqui o erro ta errado. A verificação pra user.active é UserNotAllowed

2024-08-29 13:21 UTC, MatCMartins commented on src/modules/update_action/app/update_action_usecase.py
Mesma coisa do get_history

2024-08-29 13:22 UTC, MatCMartins commented on src/modules/update_member/app/update_member_usecase.py
Mesma coisa do get_history

2024-08-29 13:22 UTC, MatCMartins commented on src/modules/update_project/app/update_project_usecase.py
Aqui o validate_role_admin pode ter o novo erro

2024-08-29 13:22 UTC, MatCMartins commented on src/shared/helpers/errors/usecase_errors.py
Legal

2024-08-29 13:25 UTC, MatCMartins requested changes
LEGAL o erro novo. Só analisem onde aplicar certinho. Tem algumas rotas que tão inconsistentes. 
*Não esqueçam de mudar os erros nos testes tbm*

2024-08-29 21:08 UTC, rruthes commented on src/modules/create_project/app/create_project_usecase.py
feito

2024-08-29 21:09 UTC, rruthes commented on src/modules/delete_project/app/delete_project_usecase.py
feito

2024-08-29 21:11 UTC, rruthes commented on src/modules/update_action/app/update_action_usecase.py
feito

2024-08-29 21:13 UTC, rruthes commented on src/modules/get_member/app/get_member_usecase.py
feito

2024-08-29 21:14 UTC, rruthes commented on src/modules/get_history/app/get_history_usecase.py
feito

2024-08-29 21:15 UTC, rruthes commented on src/modules/update_member/app/update_member_usecase.py
feito

2024-08-29 21:15 UTC, rruthes commented on src/modules/get_all_members/app/get_all_members_usecase.py
feito

2024-08-29 21:16 UTC, rruthes commented on src/modules/update_project/app/update_project_usecase.py
feito

2024-08-29 21:16 UTC, rruthes commented on src/shared/helpers/errors/usecase_errors.py
👍

2024-08-29 21:37 UTC, MatCMartins approved these changes
LGTM

2024-08-29 21:37 UTC, merged