Action refat👷‍♂️
Maua-Dev/port_mss_action pull request #20
Opened 2023-05-10 13:40 UTC by LuigiTrevisan

<h3 align="center">👷‍♂️Action Refat 👷‍♂️</h3>

<p align="center">Duration, start_date, end_date e correções gerais.</p>

**Duration:** Novo atributo na classe Action, sendo um int em milissegundos.
- Precisa ser int (óbvio)
- Precisa ser maior que 0
- Não pode ser maior que end_date - start_date

**Start/End <s>time</s> _date_:** Nome dos atributos mudados para melhor representação, já que agora o usuário poderá começar uma ação em um dia e terminar em outro, sem isso representar necessariamente o tempo que ele trabalhou naquela ação.

**Remoção do import no usecase_errors:** Sempre dava um warning no pytest e não era utilizado.
```py
from lib2to3 import Base
```

2023-05-10 22:25 UTC, JoaoVitorBranco requested changes

2023-05-10 22:25 UTC, JoaoVitorBranco commented on src/shared/domain/entities/action.py
> +            if len(description) < Action.MIN_TITLE_LENGTH or len(description) > Action.MAX_TITLE_LENGTH:
cria uma cosntante de mínimo e máximo pra _description_

2023-05-10 22:25 UTC, JoaoVitorBranco commented on tests/shared/domain/entities/test_action.py
> +            action = Action(owner_ra='17033730', start_date=1634526000, action_id='82fc', duration = 10 * 60 * 60 * 1000, associated_members_ra=['21017310', '21010757', '21010757'], title='Teste', en
testa _duration_

2023-05-10 22:25 UTC, JoaoVitorBranco commented on tests/modules/create_action/app/test_create_action_presenter.py
> +        assert response["statusCode"] == 400
add assert para msg

2023-05-11 00:17 UTC, JoaoVitorBranco approved these changes

2023-05-11 00:17 UTC, merged

2023-05-13 18:00 UTC, LuigiTrevisan commented
Faltou colocar no viewmodel e controller 🤡