rota get_all_actions_by_ra deletada
Maua-Dev/port_mss_action pull request #21
Opened 2023-05-11 15:48 UTC by Rubiozito

2023-05-17 18:49 UTC, Rubiozito commented
1 - Tirar rota get_all_actions_by_ra

2 - Adicionar story_id em Action (pode ser None, >0)

3 - actionTypeTags precisa virar actionTypeTag (vira ENUM e não List[ENUM])

4 - stackTags e actionTypeTag não pode mais ser None (Validação e testes)

2023-05-17 20:03 UTC, JoaoVitorBranco requested changes

2023-05-17 20:03 UTC, JoaoVitorBranco commented on src/shared/domain/entities/action.py
> +            if story_id < 100 or story_id > 9999:
deixa esses parâmetros (100 e 9999) como constantes da classe pra caso tenhamos que mudar futuramente

2023-05-17 20:03 UTC, JoaoVitorBranco commented on tests/shared/domain/entities/test_action.py
> +    def test_action_story_id_less_than_100(self):
less than minimum (pra caso mudemos o valor)

2023-05-17 20:03 UTC, JoaoVitorBranco commented on tests/shared/domain/entities/test_action.py
> +    def test_action_story_id_greater_than_9999(self):
greater_than_max (msm motivo)

2023-05-17 20:03 UTC, JoaoVitorBranco commented on tests/shared/domain/entities/test_action.py
> +    def test_action_story_id_not_int(self):
faz um pra ele poder ser None

2023-05-17 20:03 UTC, JoaoVitorBranco commented on src/shared/domain/entities/action.py
> +        return f'Action(owner_ra={self.owner_ra}, start_date={self.start_date}, end_date={self.end_date}, action_id={self.action_id}, title={self.title}, project_code={self.project_code}, associated_
self.action_type_tag.value()

2023-05-17 20:03 UTC, JoaoVitorBranco commented on tests/shared/domain/entities/test_action.py
> +    def test_action_action_type_tag_tags_not_enum(self):
...type_tag_not_enum

2023-05-18 00:51 UTC, JoaoVitorBranco approved these changes

2023-05-18 00:51 UTC, merged