Create Project💡
Maua-Dev/port_mss_action pull request #24
Opened 2023-06-22 23:52 UTC by LuigiTrevisan

<h1 align="center">💡 Create Project 💡</h1>
<p>Método Create para a classe Project, com <b>17</b> testes unitários totais.</p>
<p>Os testes podem ser acessados <a href="https://port-mss-action-create-project.tiiny.site">aqui</a>.

---

<p><b>ChatGPT:</b> O emoji mais apropriado para representar a ação de "Create" é 💡 (ideia). Embora não seja um emoji universalmente estabelecido para essa ação específica, o símbolo da lâmpada é frequentemente associado a novas ideias e criação, o que pode se alinhar ao conceito de criação de um novo projeto.</p>

2023-07-08 14:28 UTC, VgsStudio requested changes

2023-07-08 14:28 UTC, VgsStudio commented on src/modules/create_project/app/create_project_controller.py
> +from src.modules.create_project.app.create_project_viewmodel import CreateProjectViewmodel
corrige o import

2023-07-08 14:28 UTC, VgsStudio commented on src/modules/create_project/app/create_project_controller.py
> +        try:
futurp a gente vai ter que fazer validação de membro, ai ai que diversão ne, viva o LOGIN INTEGRADO!

2023-07-08 14:28 UTC, VgsStudio commented on src/modules/create_project/app/create_project_usecase.py
> +        # if self.repo.get_project(project_id=project.project_id) is not None:
quando vai descomentar isso?

2023-07-08 14:28 UTC, VgsStudio commented on src/modules/create_project/app/create_project_usecase.py
> +        # if self.repo.get_project(project_id=project.project_id) is not None:
cuidado pra não esquecer, fiz algumas vezes isso na sorrizo

2023-07-08 14:28 UTC, VgsStudio commented on src/modules/create_project/app/create_project_usecase.py
> +            po_RA=po_RA,
esse RA maiúsculo me da nos nervos, dps que vcs acabarem essas rotas quero um ctrl shift r pra minusculo. (mb eu tenho toque)

2023-07-08 21:17 UTC, LuigiTrevisan commented on src/modules/create_project/app/create_project_controller.py
> +from src.modules.create_project.app.create_project_viewmodel import CreateProjectViewmodel
ok

2023-07-09 01:03 UTC, JoaoVitorBranco requested changes

2023-07-09 01:03 UTC, JoaoVitorBranco commented on tests/modules/create_project/app/test_create_project_controller.py
> +        assert response.body == 'Field start_date is missing'
Faltou testar a parte de photos ser uma lista e dos valores dentro de photos serem strings. Como vc colocou isso no controller, é bom testar

2023-07-09 01:06 UTC, VgsStudio commented on tests/modules/create_project/app/test_create_project_controller.py
> +        assert response.body == 'Field start_date is missing'
sdds de vc revisando pr

2023-07-09 01:11 UTC, VgsStudio approved these changes
LGTM

2023-07-10 16:11 UTC, LuigiTrevisan commented on tests/modules/create_project/app/test_create_project_controller.py
> +        assert response.body == 'Field start_date is missing'
ok

2023-07-10 17:55 UTC, VgsStudio approved these changes
LGTM

2023-07-10 17:56 UTC, merged