Alterações member
Maua-Dev/port_mss_action pull request #25
Opened 2023-07-07 23:12 UTC by Rubiozito

'story_id' deve ser maior que 0
Converter a lista de projetos em 'Member' de 'List[Project]' para 'List[str]' com o código do projeto
Certificar que 'Member.email' é diferente de 'Member.dev_email'
Configurar 'associated_members_ra' como uma lista vazia em vez de 'None

2023-07-08 14:18 UTC, VgsStudio requested changes

2023-07-08 14:18 UTC, VgsStudio commented on README.md
> +- "test" follow by class name (ex: `test_cadastrar_usuario_valido`, `test_cadastrar_usuario_sem_email_dev`)
vc deu um replace em email por em email dev aq

2023-07-08 14:18 UTC, VgsStudio commented on src/shared/domain/entities/action.py
> +    def __init__(self, owner_ra: str, start_date: int, stack_tags: List[STACK], end_date: int, duration: int, action_id: str, title: str, project_code: str, action_type_tag: ACTION_TYPE, associated_m
tanto no contrutor, como no atributo da classe, coloca o story id sendo Optional[int]

além disso tudo que puder ser opcional faz a mesma coisa, não vai mudar nada em questão de teste ou coisa assim, é só pra gente tipar e entender melhor no futuro

2023-07-08 14:18 UTC, VgsStudio commented on src/shared/domain/entities/action.py
> +            if len(associated_members_ra) > 0:
precisa fazer essa validação da len > 0 ?

é só assimilar o valor pra variável direto!

2023-07-08 14:18 UTC, VgsStudio commented on src/shared/domain/entities/member.py
> +        if email_dev==email:
faz sentido isso? 
por que não pode ser o mesmo email? 
a gente tem que MARCAR sendo coisas diferentes, mas acho que não tem problema ser igual. (vamos verificar com o fernando)

vai que o cara se cadastra no login integrado com o email dele?

2023-07-08 14:18 UTC, VgsStudio commented on src/shared/infra/dto/user_dynamo_dto.py
>  class UserDynamoDTO:
ja temos um DTO de user?
chegamos a montar uma tabela?

vamos TROCAR email por email dev?
eu acho que tenha que ter OS DOIS, além de outros valores do usuário

além disos o user_id tem que ser uma STR e não int

2023-07-08 14:18 UTC, VgsStudio commented on src/shared/domain/entities/member.py
>      hired_date: int # milliseconds
esses negócios de data em miliseconds faz uma validação (luigi fez na smile olha la na activity)

2023-07-10 11:54 UTC, Rubiozito commented on README.md
> +- "test" follow by class name (ex: `test_cadastrar_usuario_valido`, `test_cadastrar_usuario_sem_email_dev`)
Replace automático sorry, essa ai passoue sem eu ver

2023-07-10 12:06 UTC, Rubiozito commented on src/shared/domain/entities/action.py
> +            if len(associated_members_ra) > 0:
Ok

2023-07-10 12:18 UTC, Rubiozito commented on src/shared/domain/entities/action.py
> +            if len(associated_members_ra) > 0:
Ok

2023-07-10 13:39 UTC, Rubiozito commented on src/shared/domain/entities/member.py
> +        if email_dev==email:
Ok

2023-07-10 13:48 UTC, Rubiozito commented on src/shared/domain/entities/member.py
>      hired_date: int # milliseconds
Ok

2023-07-10 16:07 UTC, Rubiozito commented on src/shared/domain/entities/action.py
> +    def __init__(self, owner_ra: str, start_date: int, stack_tags: List[STACK], end_date: int, duration: int, action_id: str, title: str, project_code: str, action_type_tag: ACTION_TYPE, associated_m
ok

2023-07-10 17:52 UTC, VgsStudio approved these changes
LGTM

2023-07-10 18:26 UTC, merged