Delete project ❌
Maua-Dev/port_mss_action pull request #26
Opened 2023-07-08 13:27 UTC by LuigiTrevisan

<h1 align="center">❌ Create Project ❌</h1>
<p>Método Delete para a classe Project, com <b>14</b> testes unitários totais.</p>
<p>Os testes podem ser acessados <a href="https://port-mss-action-delete-project.tiiny.site">aqui</a>.

---

<p><b>ChatGPT:</b> O emoji mais apropriado para representar a ação de "Delete" é ❌ (símbolo de "X" vermelho). Esse emoji é amplamente utilizado para indicar remoção, exclusão ou cancelamento. O símbolo "X" vermelho é visualmente reconhecido como um indicador de encerramento ou eliminação, sendo comumente associado à ação de excluir algo. Portanto, o emoji ❌ é adequado para representar a ação de "Delete".</p>

2023-07-08 14:24 UTC, VgsStudio requested changes

2023-07-08 14:24 UTC, VgsStudio commented on .gitignore
> +module_creation_inline.py
quente

2023-07-08 14:24 UTC, VgsStudio commented on .gitignore
> +module_creation_inline.py
(pycharm faz isso sozinho ta

2023-07-08 14:24 UTC, VgsStudio commented on src/shared/domain/entities/project.py
> +            self.photos = []
pq vc n seta no construtor sendo uma lista vazia direto? 
eu acho meio ruim vc DEIXAR que coloquem none pra ai vc colocar a lista vazia

2023-07-08 14:24 UTC, VgsStudio commented on src/shared/domain/repositories/action_repository_interface.py
> +    def delete_project(self, code: str) -> Project:
explica em comentario na interface como que deve ser implemetado o método. No momneto vcs tão usando só o mock, e colocam o comportamento de por exemplo se não existe retornar None. Mas amanhã ou dps vcs vão lembrar? Não.

Coloca uma docstring explicando o que o método faz e fala que se não acahar retorna None.
Ale´m disso coloca ali que ele retorna um Optional[Project], quem dizer ele opcionalmente retorna Project, isso a gente vai coemçar a coloca pra tudo .

2023-07-08 14:49 UTC, LuigiTrevisan commented on .gitignore
> +module_creation_inline.py
🤯

2023-07-08 14:49 UTC, LuigiTrevisan commented on src/shared/domain/entities/project.py
> +            self.photos = []
ok

2023-07-08 14:51 UTC, LuigiTrevisan commented on src/shared/domain/repositories/action_repository_interface.py
> +    def delete_project(self, code: str) -> Project:
ok

2023-07-09 00:53 UTC, JoaoVitorBranco approved these changes

2023-07-09 01:08 UTC, JoaoVitorBranco commented on .gitignore
> +module_creation_inline.py
comentários ruins devem ser apagados 😎

2023-07-09 01:11 UTC, merged