Refat-memberXproject
Maua-Dev/port_mss_action pull request #39
Opened 2023-08-11 03:29 UTC by Rubiozito

a entidade member não possui mais uma lista com os códigos dos projetos que participa. A entidade project agora possui uma lista com os RA's dos membros participante do projeto, que obrigatoriamente deve incluir os RA's do po e scrum. Isso também implica em pequenas mudanças em algumas rotas

2023-08-12 22:19 UTC, VgsStudio requested changes
REFAT muito bom, só arruma essa coisinha que eu marquei.

Vou dar merge no pr do luigi primeiro depois vc arruma o que quebrar e conflitos, aí dou merge no seu OK?

2023-08-12 22:19 UTC, VgsStudio commented on src/modules/create_action/app/create_action_controller.py
> +                for ra in request.data.get('associated_members_ra'):
Verifica se é uma lista antes

2023-08-13 03:38 UTC, Rubiozito commented on src/modules/create_action/app/create_action_controller.py
> +                for ra in request.data.get('associated_members_ra'):
Verificado

2023-08-14 13:45 UTC, VgsStudio approved these changes

2023-08-14 13:45 UTC, merged