Member crud
Maua-Dev/port_mss_action pull request #51
Opened 2023-10-02 23:09 UTC by joae1234

2023-10-03 22:14 UTC, Rubiozito requested changes

2023-10-03 22:14 UTC, Rubiozito commented on src/modules/create_member/app/create_member_controller.py
> +
Esqueceram de apagar os comentários do action aqui

2023-10-03 22:14 UTC, Rubiozito commented on src/modules/create_member/app/create_member_controller.py
> +                # role=request.data.get('role'),
Outro comentário que não deveria estar aqui

2023-10-03 22:14 UTC, Rubiozito commented on src/modules/create_member/app/create_member_controller.py
> +                # active=request.data.get('active'),
active não deveria estar comentado, faz parte da entidade, descomenta e roda os testes de novo pra ver se ta funcionando

2023-10-03 22:14 UTC, Rubiozito commented on src/modules/create_member/app/create_member_controller.py
> +                # stack_tags=stack_tags,
Mais comentários que não eram pra estar aqui...

2023-10-03 22:14 UTC, Rubiozito commented on src/modules/create_member/app/create_member_usecase.py
> +    def __call__(self, ra: str, name: str, email_dev: str , email: str, role: ROLE, stack: STACK, year: int, cellphone: str, course: COURSE, hired_date: int, deactivated_date: int) -> Member:
deactivated_date por padrão é none

2023-10-03 22:14 UTC, Rubiozito commented on src/modules/update_member/app/update_member_usecase.py
> +    def __call__(self, ra: str, new_name: Optional[str] = None, new_email_dev: Optional[str] = None, new_email: Optional[str] = None, new_role: Optional[ROLE] = None, new_stack: Optional[STACK] = Non
new hired date não faz sentido né? a data de admissão não muda
Só teria esse parametro no update caso fosse um hard update, não é o caso

2023-10-03 22:14 UTC, Rubiozito commented on src/modules/update_member/app/update_member_usecase.py
> +        # members = None
Mais comentário perdido no meio do código

2023-10-03 22:14 UTC, Rubiozito commented on src/shared/infra/repositories/member_repository_mock.py
> +                if new_hired_date is not None:
só repetindo, new hired date não faz sentido, esse atributo não sofre alterações após a criação da entidade

2023-10-03 22:14 UTC, Rubiozito commented on src/shared/infra/repositories/member_repository_mock.py
> +                if new_email_dev is not None:
Os emails também não sofrem update, tira do resto da rota também

2023-10-03 22:14 UTC, Rubiozito commented on tests/modules/create_member/app/test_create_member_controller.py
> +        # assert response.body['member']['active'] == ACTIVE.ACTIVE.value
Por que isso ta comentado? faz a validação se após criar o status é active

2023-10-03 22:14 UTC, Rubiozito commented on tests/modules/create_member/app/test_create_member_controller.py
> +    def test_create_action_controller_missing_title(self):
Esqueceram de tirar esses teste do action que sinceramente não sei o que ta fazendo aqui, apaga isso

2023-10-03 22:14 UTC, Rubiozito commented on tests/modules/create_member/app/test_create_member_controller.py
> +
façam validações pra ver se levanta erro quando tem valores errados

2023-10-03 22:14 UTC, Rubiozito commented on src/modules/create_member/app/create_member_controller.py
> +
Falta validação de parametro aqui no controller né?
Da uma olhada aqui e na entidade do member, tem um método do member de validação que deveria estar aqui, reflitam e me chamem qualquer coisa

2023-10-03 22:14 UTC, Rubiozito commented on tests/modules/delete_member/app/test_delete_member_usecase.py
> +
Faz um teste pra verificar se levanta erro com ra inexistente

2023-10-03 22:14 UTC, Rubiozito commented on tests/modules/update_member/app/test_update_member_usecase.py
> +#  ra: str, new_name: Optional[str] = None, new_email_dev: Optional[str] = None, new_email: Optional[str] = None, new_role: Optional[ROLE] = None, new_stack: Optional[STACK] = None, new_year: Optiona
De novo comentário que não deveria estar aqui

2023-10-03 22:14 UTC, Rubiozito commented on tests/shared/infra/repositories/test_member_repository_mock.py
> +
Cade o teste do método update?

2023-10-05 01:04 UTC, Rubiozito requested changes

2023-10-05 01:04 UTC, Rubiozito commented on src/shared/infra/repositories/member_repository_mock.py
> +            Member(
A gente não tem nenhum membro com um deactivated_date, coloca esse com um, pode ser interessante pros testes ( Atenção com o time-stamp)

2023-10-05 01:04 UTC, Rubiozito commented on tests/modules/update_member/app/test_update_member_controller.py
> +
faz um teste pra dar update na deactivated_date, ve se funciona e verifica também se levanta erro caso a data de desligamento seja antes da data de admissão

2023-10-05 01:04 UTC, Rubiozito commented on tests/modules/update_member/app/test_update_member_viewmodel.py
> +                'email':"vsoller@airubio.com",
o email não muda então não tem pq aparecer

2023-10-05 01:04 UTC, Rubiozito commented on tests/modules/update_member/app/test_update_member_controller.py
> +             'ra': ra,
ajeita esse espaço antes do ra aqui

2023-10-05 01:04 UTC, Rubiozito commented on tests/modules/update_member/app/test_update_member_controller.py
> +            'new_name':"Joao Branco",
Pensa aqui comigo, se você vai testar um método de update, você não pode fazer isso usando exatamente os mesmo valores que ja estão no repo_mock né?
Como você vai saber se o método ta funcionando e o valor foi alterado com sucesso se você não colocou **nenhum** valor diferente?

2023-10-05 01:04 UTC, Rubiozito commented on src/shared/infra/repositories/member_repository_mock.py
> +                if new_email_dev is not None:
Só reforçando aqui, o **email** não sofre update, o email_dev pode sofre update sim

2023-10-05 01:04 UTC, Rubiozito commented on src/modules/update_member/app/update_member_controller.py
> +            new_deactivated_date = request.data.get('new_deactivated_date')
data do desligamento não pode ser menor que a data de admissão

2023-10-05 18:18 UTC, joae1234 commented on src/modules/create_member/app/create_member_controller.py
> +
Resolvido

2023-10-05 18:18 UTC, joae1234 commented on src/modules/create_member/app/create_member_usecase.py
> +    def __call__(self, ra: str, name: str, email_dev: str , email: str, role: ROLE, stack: STACK, year: int, cellphone: str, course: COURSE, hired_date: int, deactivated_date: int) -> Member:
Resolvido

2023-10-05 18:19 UTC, joae1234 commented on src/modules/update_member/app/update_member_usecase.py
> +        # members = None
Consertado

2023-10-05 18:20 UTC, joae1234 commented on src/shared/infra/repositories/member_repository_mock.py
> +                if new_email_dev is not None:
Consertado

2023-10-05 18:20 UTC, joae1234 commented on tests/modules/create_member/app/test_create_member_controller.py
> +        # assert response.body['member']['active'] == ACTIVE.ACTIVE.value
Consertado

2023-10-05 18:21 UTC, joae1234 commented on tests/modules/create_member/app/test_create_member_controller.py
> +    def test_create_action_controller_missing_title(self):
Consertado

2023-10-05 18:21 UTC, joae1234 commented on src/modules/create_member/app/create_member_controller.py
> +
Consertado

2023-10-05 18:22 UTC, joae1234 commented on tests/modules/update_member/app/test_update_member_usecase.py
> +#  ra: str, new_name: Optional[str] = None, new_email_dev: Optional[str] = None, new_email: Optional[str] = None, new_role: Optional[ROLE] = None, new_stack: Optional[STACK] = None, new_year: Optiona
Consertado

2023-10-05 19:17 UTC, joae1234 commented on tests/shared/infra/repositories/test_member_repository_mock.py
> +
Resolvido

2023-10-05 19:51 UTC, joae1234 commented on tests/modules/update_member/app/test_update_member_controller.py
> +
Corrigido

2023-10-05 19:57 UTC, joae1234 commented on src/modules/update_member/app/update_member_controller.py
> +            new_deactivated_date = request.data.get('new_deactivated_date')
Corrigido

2023-10-05 19:57 UTC, joae1234 commented on tests/modules/update_member/app/test_update_member_controller.py
> +            'new_name':"Joao Branco",
Corrigido

2023-10-05 19:57 UTC, joae1234 commented on tests/modules/update_member/app/test_update_member_controller.py
> +             'ra': ra,
Corrigido

2023-10-05 19:57 UTC, joae1234 commented on tests/modules/update_member/app/test_update_member_viewmodel.py
> +                'email':"vsoller@airubio.com",
Corrigido

2023-10-05 22:07 UTC, joae1234 commented on tests/modules/create_member/app/test_create_member_controller.py
> +
Corrigido

2023-10-05 23:33 UTC, joae1234 commented on src/shared/infra/repositories/member_repository_mock.py
> +            Member(
corrigido

2023-10-06 00:40 UTC, Rubiozito requested changes

2023-10-06 00:40 UTC, Rubiozito commented on tests/modules/update_member/app/test_update_member_usecase.py
> +
faz mais 1 ou 2 testes dando update em apenas um parametro

2023-10-06 00:40 UTC, Rubiozito commented on tests/modules/update_member/app/test_update_member_controller.py
> +
Mesma coisa aqui, faz teste tentando dar update em apenas uma coisa

2023-10-06 19:34 UTC, joae1234 commented on tests/modules/update_member/app/test_update_member_controller.py
> +
Corrigido

2023-10-06 19:34 UTC, joae1234 commented on tests/modules/update_member/app/test_update_member_usecase.py
> +
Corrigido

2023-10-10 13:59 UTC, Rubiozito requested changes

2023-10-10 13:59 UTC, Rubiozito commented on tests/modules/update_member/app/test_update_member_controller.py
> +    def test_update_Member_controller(self):
Ajeita esses nomes de testes que ta "Member" ao invés de 'member'

2023-10-10 13:59 UTC, Rubiozito commented on tests/modules/update_member/app/test_update_member_usecase.py
> +    def test_update_member_usecase_new_year(self):
Ano 35? isso não faz nem sentido, não deveria nem ser aceito, não existe curso na mauá com duração maior q 6 anos

2023-10-10 19:42 UTC, joae1234 commented on tests/modules/update_member/app/test_update_member_controller.py
> +    def test_update_Member_controller(self):
Corrigido

2023-10-10 19:42 UTC, joae1234 commented on tests/modules/update_member/app/test_update_member_usecase.py
> +    def test_update_member_usecase_new_year(self):
Corrigido

2023-10-10 20:22 UTC, Rubiozito approved these changes

2023-10-10 20:32 UTC, VgsStudio approved these changes
RUBI REVISOU

2023-10-10 20:33 UTC, VgsStudio approved these changes
RUBI REVISOU

2023-10-10 20:34 UTC, merged