Requester user
Maua-Dev/port_mss_action pull request #54
Opened 2023-11-09 00:15 UTC by GabrielBianconiconi

2023-11-16 15:03 UTC, Rubiozito requested changes

2023-11-16 15:03 UTC, Rubiozito commented on src/modules/create_member/app/create_member_usecase.py
> +        return self.repo.create_member(member)
retorna o member, ja ta criando ele 3 linhas acima

2023-11-16 15:03 UTC, Rubiozito commented on src/shared/domain/repositories/member_repository_interface.py
> +    def delete_member(self, user_id: str) -> Optional[Member]:
Cuidado com mudar a interface pra não tomar erro quando for fazer o repo dynamo

2023-11-16 15:03 UTC, Rubiozito commented on tests/modules/create_member/app/test_create_member_controller.py
> +        assert response.status_code == 500
Pq colocou 500 aqui? e pq tirou a mensagem de resposta?

2023-11-16 15:03 UTC, Rubiozito commented on tests/modules/create_member/app/test_create_member_controller.py
> +        assert response.status_code == 500
mudou o erro dnv

2023-11-16 15:03 UTC, Rubiozito commented on tests/modules/create_member/app/test_create_member_controller.py
> +        assert response.status_code == 500
mudou o erro dnv

2023-11-19 16:02 UTC, joae1234 commented on tests/modules/create_member/app/test_create_member_controller.py
> +        assert response.status_code == 500
Resolvido

2023-11-19 16:02 UTC, joae1234 commented on tests/modules/create_member/app/test_create_member_controller.py
> +        assert response.status_code == 500
Resolvido

2023-11-19 16:02 UTC, joae1234 commented on tests/modules/create_member/app/test_create_member_controller.py
> +        assert response.status_code == 500
Resolvido

2024-02-16 17:37 UTC, Rubiozito requested changes

2024-02-16 17:37 UTC, Rubiozito commented on src/modules/create_member/app/create_member_controller.py
> +            # if type(str(requester_user.name)) is not str:
Esse Comentário aqui... ??

2024-02-16 17:37 UTC, Rubiozito commented on tests/modules/create_member/app/test_create_member_controller.py
> -    def test_create_member_controller_missing_name(self):
pq esse teste foi apagado?

2024-02-16 17:45 UTC, Rubiozito approved these changes

2024-02-16 18:03 UTC, joae1234 commented on tests/modules/create_member/app/test_create_member_controller.py
> -    def test_create_member_controller_missing_name(self):
> pq esse teste foi apagado?

Pelo que me foi explicado, não se testa a ausência de parâmetros que fazem parte do request_user, já q são dados que chegam de fora, até chequei no Maua food e eles tbm não testam a ausência de parâmetros do request_user, mas testam a a falta do próprio request_user. Então deletei esse teste pois ele é desnecessário

2024-02-16 18:08 UTC, joae1234 commented on src/modules/create_member/app/create_member_controller.py
> +            # if type(str(requester_user.name)) is not str:
> Esse Comentário aqui... ??

Como esses testes são de um parametro do request_user, eles são desnecessarios, então eu tinha esquecido de remover, agora foram removidos

2024-02-21 00:17 UTC, merged